"""Generates rage_data.h: the offline-verified tables the in-process controller needs.

Sources: attack_inventory.json (player ALS records), anim_hashes.json (animation
hashes) and the clip_swaps from rage_config.json. Re-run after changing any of them.
"""
import json
from pathlib import Path

HOME = Path(__file__).resolve().parent
inv = json.loads((HOME / 'attack_inventory.json').read_text())['records']
anim = json.loads((HOME / 'anim_hashes.json').read_text())
config = json.loads((HOME / 'rage_config.json').read_text(encoding='utf-8'))

SELECTED = ['smbrightpunch', 'smbrightpunch_nc', 'smbleftpunch', 'smbrightelbow',
            'smbstomp', 'smbstomp_nc', 'smbbackhandender', 'smbrun2leftpunch']
out = ['// Generated by make_rage_data.py. Do not edit by hand.', '#pragma once', '']

def record(name):
    return next(r for r in inv if r['name'] == name)

for name, var in (('smbichorwhipr', 'WhipR'), ('smbichorwhipl', 'WhipL')):
    r = record(name)
    out.append(f'static constexpr unsigned {var}NameOffset=0x{r["name_offset"]:X}, {var}AnimHash=0x{r["anim_hash"]};')
out.append('')

# Ground attack nodes: node hash plus every reference offset inside the ALS.
nodes = sorted({r['node_hash'] for r in inv if r['name'] in SELECTED})
out.append('struct GroundRef { unsigned nodeHash, whipHash, offset; };')
out.append('static const GroundRef groundRefs[] = {')
for i, node_hash in enumerate(nodes):
    whip = 0xF751E2C5 if i % 2 else 0xF751E2C4
    offsets = sorted({o for r in inv if r['node_hash'] == node_hash for o in r['references']})
    for o in offsets:
        out.append(f' {{0x{node_hash}, 0x{whip:08X}, 0x{o:X}}},')
out.append('};')
out.append('')

out.append('struct ClipSwap { const char* ground; unsigned groundHash; const char* wall; unsigned wallHash; };')
out.append('static const ClipSwap clipSwaps[] = {')
for ground, wall in config['clip_swaps'].items():
    out.append(f' {{"{ground}", 0x{anim[ground]:08X}, "{wall}", 0x{anim[wall]:08X}}},')
out.append('};')
(HOME / 'rage_data.h').write_text('\n'.join(out) + '\n', encoding='ascii')
print('rage_data.h:', len(nodes), 'ground nodes,', len(config['clip_swaps']), 'clip swaps')
